### ISSUE TITLE
Error when using in Wails：[SSR Router - r86fbc1ba]"Navigation error"

### ISSUE THREAD

**Issue by jc955** [dvcol/svelte-simple-router#1]
```js
// App.svelte
<script lang="ts">
  import { RouterView } from '@dvcol/svelte-simple-router/components'

  const routes = [
    {
      component: () => import('./A.svelte'),
      name: 'home',
      path: '/',
    },
    {
      component: () => import('./B.svelte'),
      name: 'b',
      path: '/b',
    },
  ] as const

  const options = {
    routes,
  } as const
</script>

<RouterView {options} />
```

hello @dvcol 

The same code works in Electron but throws an error in [wails](https://github.com/wailsapp/wails).

  [SSR Router - r86fbc1ba]"Navigation error"
  Unhandled Promise Rejection: Error: Navigation failed: NAVIGATION_ABORTED

![image](https://github.com/user-attachments/assets/c0512595-5b8c-4679-9cef-a54e9e03ce44)

**Comment by dvcol** [comment]
From the error stacks, it seems that the `Promise` prototype doesn't have `withResolvers()`.

Support is [quite good](https://caniuse.com/mdn-javascript_builtins_promise_withresolvers) on the browser side, but maybe you might need a polyfill for wails?
