### ISSUE TITLE
[Feature Request] `links` action

### ISSUE THREAD

**Issue by RingOfStorms** [dvcol/svelte-simple-router#11]
I would love if you added a top level `use:links` that works like [this router](https://github.com/jpcutshall/svelte5-router/tree/master?tab=readme-ov-file#links) ([code](https://github.com/jpcutshall/svelte5-router/blob/master/src/lib/actions.ts#L39-L56))
So that by default any anchors as a child under the `use:links` will use the router, instead of needing to put `use:link` on every anchor manually.

**Comment by dvcol** [comment]
Hey !

Sure, I threw something together in this [PR](https://github.com/dvcol/svelte-simple-router/pull/12).

I'd still recommend using the `use:link` action instead for a few reasons:
- More declarative and easier to track what's in scope or not
- `use:link` also normalize attributes and adds role, href & tabindex if they are missing (for acessibility)
- Listening to all inner `click` and `keydown.enter `events means, that any button or event listener that are wrapped inside a use-link will require to capture thir events to prevent bubling to the host.

Also, note that navigating up and down the DOM tree on each click event might cause performance problems on big application.

Hoping this helps (despite those limitations) :)

**Comment by RingOfStorms** [comment]
@dvcol I think you forgot to export `links` https://github.com/dvcol/svelte-simple-router/blob/main/src/lib/router/index.ts
